# JUST A SAMPLE
jwt:
  access:
    key: SAMPLE_ACCESS_KEY
    expiration: SAMPLE_ACCESS_EXPIRATION_TIME_IN_MINUTE
  refresh:
    key: SAMPLE_REFRESH_KEY
    expiration: SAMPLE_REFRESH_EXPIRATION_TIME_IN_MINUTE