# JUST A SAMPLE
jwt:
  secret:
    key: SAMPLE_SECRET_KEY
    expiration: SAMPLE_SECRET_EXPIRATION_TIME_IN_MINUTE
  refresh:
    key: SAMPLE_REFRESH_KEY
      expiaration: SAMPLE_REFRESH_EXPIRATION_TIME_IN_MINUTE